name: AWS Assume Role
description: Assumes an IAM Role before running the build command.
author: https://github.com/cultureamp
requirements:
  - aws
configuration:
  properties:
    role:
      type: string
  additionalProperties: false
